In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index # como range (4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index


Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
# index 'a' está na linha de -5.
obj2 ['a']

-5

In [11]:
# Alterei o valor de 4 para 6 no index 'd'.
obj2 ['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

 Nesse caso, ['c', 'a', 'd'] é interpretado como uma lista de índices, apesar de conter strings em vez de inteiros.

In [13]:
# -5 não é maior que > 0 então não irá aparecer.
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
#  Multiplicando os valores:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
# Conferindo se está na variável
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
# Se você tiver dados contidos em um dicionário python, uma series poderá ser criada a partir dele, passando-lhe o dicionário:

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000 }

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = pd.Series(sdata, index=states)

In [23]:
# Imprimindo na ordem que escrevi: 
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
# California com valor nulo:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
# Que não tem valor nulo:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
# Uma Series também tem esses métodos como métodos de instância: 

obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
# Unir valores das duas variáveis:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population' 

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [35]:
# Um índice de Series pode ser alterado in-place por atribuição:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [36]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [37]:
# Exibindo dataframe de acordo com os valores e nome:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [38]:
# Para DataFrames grandes, o método head selecionará somente as primeiras cinco linhas:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [39]:
# Exibir na sequência que escrevi:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [40]:
# Se você passar uma coluna que não esteja contida no dicionário, ela aparecerá com valores ausentes no resultado:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four',
                           'five', 'six'])

In [41]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
#Uma coluna em um DataFrame pode ser obtida como uma Series, seja usando uma notação do tipo dicionário ou por meio de atributo:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [45]:
# Com base na posição ou no nome com loc
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
# As colunas podem ser modificadas por atribuição. Por exemplo, a coluna vazia 'debt' poderia receber um valor escalar ou um array de valores:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6.)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [50]:
# Inserindo valores no index:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [51]:
frame2['debt'] = val # Os valores vão ficar na coluna debt

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [53]:
# Criando uma nova coluna em que onde tiver 'Ohio' seja True:
frame2['eastern'] = frame2.state == 'Ohio'

In [54]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [55]:
# Removendo coluna:
del frame2['eastern']

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
# Outro formato comum é um dicionário de dicionários aninhados:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [58]:
''' Se o dicionário aninhado for passado para o DataFrame, o pandas interpretará as chaves do dicionário mais externo 
como as colunas e as chaves mais internas como os índices das linhas:'''
frame3 = pd.DataFrame(pop) # Estou criando um dataframe apartir do dicionário pop.

In [59]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [60]:
# Podemos fazer a transposição do DataFrame (trocar linhas e colunas) com uma sintaxe semelhante àquela usada em um array NumPy:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [61]:
''' Usando a função dataframe da biblioteca pandas, querendo o dicionário pop para exibir os índices, mas o que foi criado
agora o resultado fica com NaN''' 
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
# Dicionários de Series são tratados praticamente do mesmo modo:
pdata = {'Ohio': frame3['Ohio'][:-1], 
        'Nevada': frame3['Nevada'][:2]} 

In [63]:
# Passando para dataframe e exibindo:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [64]:
# Inseri o nome 'year' no index e na coluna 'state', isso pode servir se no topo tem estado e abaixo tem cidade.
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [65]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [66]:
# Como ocorre com Series, o atributo values devolve os dados contidos no DataFrame como um ndarray bidimensional:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [68]:
''' Se as colunas do DataFrame tiverem dtypes distintos, o dtype do array de valores será escolhido de modo a acomodar todas
as colunas:'''
frame2.values


array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [73]:
# Através da função Series do pandas eu quero criar um indice de 3 sendo a, b e c:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [74]:
index = obj.index

In [75]:
index

Index(['a', 'b', 'c'], dtype='object')

In [77]:
# Exibir depois do um em diante:
index[1:]

Index(['b', 'c'], dtype='object')

In [78]:
# Os objetos Index são imutáveis e, desse modo, não podem ser modificados pelo usuário:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [80]:
# A imutabilidade faz com que seja mais seguro compartilhar objetos Index entre estruturas de dados:
'''A função np.arange(3) cria um array numpy que contém os valores [0, 1, 2]. Esse array é então passado 
para a função pd.Index(), que cria um objeto Index a partir desses valores.'''
labels = pd.Index(np.arange(3))

In [81]:
labels

Index([0, 1, 2], dtype='int32')

In [86]:
'''O primeiro argumento [1.5, -2.5, 0] é uma lista de valores que serão armazenados na Series. Os valores são 1.5, -2.5 e 0.

O segundo argumento index=labels especifica os rótulos (ou índices) associados a cada valor na Series.
labels é o objeto Index que criamos anteriormente, contendo os valores [0, 1, 2].'''

obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [87]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [88]:
obj2.index is labels

True